trigger:
- infra
pool:
  vmImage: 'macOS-latest'
  
jobs:
- job: Build
  displayName: 'Build Android Debug'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '21.6.2'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'Install Node.js dependencies with Yarn'

  - script: yarn cache clean
    displayName: 'Clean Yarn cache'

  - script: cd android
    displayName: 'Navigate to Android directory'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'android/gradlew'
      options: 'clean'
      tasks: 'clean'
    displayName: 'Clean Gradle cache'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'android/gradlew'
      options: '--stacktrace --info'
      tasks: 'assembleDebug'
      workingDirectory: 'android'
    displayName: 'Build Android Debug APK'