# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Build_Android
    displayName: 'Build Android App'
    steps:
      - task: UseNode@1
        inputs:
          version: '18.x'

      - script: |
          yarn install
        displayName: 'Install dependencies'

      - script: |
          cd android
          ./gradlew assembleRelease
        displayName: 'Build Android Release'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'android/app/build/outputs/apk/release/app-release.apk'
          ArtifactName: 'android-release-apk'
          publishLocation: 'Container'
