# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - infra

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Build_Android
    displayName: 'Build Android App'
    steps:
      # - task: UseNode@1
      #   inputs:
      #     version: '20'

      - script: |
          sudo update-alternatives --set java $(update-alternatives --list java | grep java-11)
          sudo update-alternatives --set javac $(update-alternatives --list javac | grep java-11)
          java -version
          javac -version
        displayName: 'Set Java 11'

      - script: |
          brew install cocoapods
          brew install node@20
          brew link node@20
          brew install yarn
          corepack enable
          yarn set version stable
          yarn
        displayName: 'Install dependencies'

      # - task: Gradle@2
      #   inputs:
      #     workingDirectory: 'src/android'
      #     gradleWrapperFile: 'src/android/gradlew'
      #     gradleOptions: '-Xmx3072m'
      #     publishJUnitResults: false
      #     testResultsFiles: '**/TEST-*.xml'
      #     tasks: 'assembleRelease'

      # - task: AndroidSigning@2
      #   inputs:
      #     apkFiles: '**/*.apk'
      #     jarsign: true
      #     jarsignerKeystoreFile: 'android.keystore'
      #     jarsignerKeystorePassword: 'kishore123'
      #     jarsignerKeystoreAlias: 'react-native-pipeline-key'
      #     jarsignerKeyPassword: 'kishore123'
      #     zipalign: true

      # - script: mv src/android/app/build/outputs/apk/release/app-release-unsigned.apk ReactNativePipeline$(Build.BuildNumber).apk
      #   displayName: 'Rename apk'

      # - script: |
      #     cd android
      #     ./gradlew clean assembleRelease
      #   displayName: 'Build Android Release'

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: ReactNativePipeline$(Build.BuildNumber).apk
      #     ArtifactName: 'android-release-apk'
      #     publishLocation: 'Container'


      - script: |
          cd android
          ./gradlew assembleDebug
        displayName: 'Build Android Debug APK'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/android/app/build/outputs/apk/debug/'
          artifact: 'drop'
        displayName: 'Publish Debug APK'
